# EmpireWand - Wand Settings Configuration
# This file defines per-wand configuration settings that can be modified through the GUI
#
# Settings explanation:
# - cooldownBlock: When true, players cannot cast spells while any spell is on cooldown
# - griefBlockDamage: When true, spells can damage/modify world blocks
# - playerDamage: When true, spells can damage other players
# - difficulty: Controls spell power and restrictions (EASY, MEDIUM, HARD)

version: "1.0.0"

# Default wand configurations
wands:
  empirewand:
    cooldownBlock: false
    griefBlockDamage: true
    playerDamage: true
    difficulty: "MEDIUM"

  mephidantes_zeist:
    cooldownBlock: false
    griefBlockDamage: true
    playerDamage: true
    difficulty: "MEDIUM"

# Default settings applied to new wands
defaults:
  cooldownBlock: false
  griefBlockDamage: true
  playerDamage: true
  difficulty: "MEDIUM"