# EmpireWand main configuration

config-version: 1.0

messages:
  no-permission: "<red>You don't have permission to do that."
  no-line-of-sight: "<red>You can't see your target."
  wand-received: "<green>You have received an Empire Wand!"
  spell-bound: "<green>Bound spell {spell} to your wand."
  spell-unbound: "<green>Unbound spell {spell} from your wand."
  all-spells-bound: "<green>Bound all available spells to your wand."
  no-spells-bound: "<red>No spells bound!"
  spell-selected: "<gray>Selected: <aqua>{spell}"
  on-cooldown: "<red>That spell is on cooldown! Wait {remaining} seconds."
  fizzle: "<gray>...fizzle..."
  wand:
    no-spells: "Je wand heeft geen spells ingesteld."
    unknown-spell: "Onbekende spreuk."
    no-permission: "Je hebt geen toestemming voor deze spreuk."
    cannot-cast: "Je kunt deze spreuk nu niet gebruiken."
    cast-error: "Er ging iets mis tijdens het casten."
    on-cooldown: "Wacht nog {seconds}s."
    swap-blocked: "Wisselen naar offhand is uitgeschakeld voor de wand."
    drop-blocked: "Je kunt de wand niet droppen."

features:
  block-damage: true
  friendly-fire: true

cooldowns:
  default: 500 # in milliseconds

# Metrics and analytics (opt-in)
metrics:
  enabled: true   # Set to false to disable bStats metrics collection
  debug: false    # Set to true to enable additional debug metrics
  plugin-id: 27206  

# Custom spell categories for convenience commands like /ew bindcat <category>
# Provide lists of spell keys to bind together. Keys must match those in spells.yml
categories:
  empire:
    spells:
      - empire-launch
      - empire-escape
      - empire-aura
      - empire-comet
      - empire-levitate
  dark:
    spells:
      - dark-circle
      - dark-pulse
      - shadow-cloak
      - shadow-step
  magic:
    spells:
      - magic-missile
      - arcane-orb
      - polymorph
      - ritual-of-unmaking
  support:
    spells:
      - heal
      - radiant-beacon
      - god-cloud
      - blood-barrier
  lightning:
    spells:
      - chain-lightning
      - lightning-bolt
      - lightning-arrow
      - lightning-storm
      - spark
      - little-spark
      - thunder-blast
      - solar-lance
  fire:
    spells:
      - fireball
      - flame-wave
      - blaze-launch
      - explosive
      - explosion-trail
  ice:
    spells:
      - frost-nova
      - glacial-spike
  earth:
    spells:
      - sandstorm
      - grasping-vines
      - earth-quake
      - lightwall
  weather:
    spells:
      - gust
      - tornado
  movement:
    spells:
      - teleport
      - blink-strike
      - sunburst-step
  projectile:
    spells:
      - comet
      - comet-shower
  aura:
    spells:
      - empire-aura
  control:
    spells:
      - polymorph
      - confuse
      - stasis-field
  poison:
    spells:
      - poison-wave
      - mephidic-reap
  life:
    spells:
      - life-reap
      - life-steal
  heal:
    spells:
      - heal
      - radiant-beacon
  enhanced:
    spells:
      - fireball-enhanced
      - comet-enhanced
      - heal-enhanced
      - meteor-shower-enhanced
      - blizzard-enhanced
      - teleport-enhanced
      - chain-lightning-enhanced
  toggle:
    spells:
      - kaj-cloud
      - mephi-cloud
      - empire-aura
