name: CI

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'
      - '**/*.txt'
      - '**/*.TXT'
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'
      - '**/*.txt'
      - '**/*.TXT'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build with Gradle 9.0
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '9.0'
          arguments: build --stacktrace

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: empirewand-artifacts
          path: build/libs/*.jar
