name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build with Gradle 8.10.2
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.10.2'
          arguments: build --stacktrace

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: empirewand-artifacts
          path: build/libs/*.jar
